### ISSUE TITLE
How to use wid_area_codes ?

### ISSUE THREAD

**Issue by clukewatson** [WIDworld/wid-r-tool#6]
Howdy,

I am downloading all areas for a given year and variable, but do not know all the codes. How do I use **wid_area_codes**? 

Ideally, **download_wid** would have an option: `fullnames =T`.
Alternatively, perhaps an option to download the cross-walk and then merge: `names <- wid::wid_area_codes`

Otherwise, thank you for making this tool available!

Best,
Luke

**Comment by thomasblanchet** [comment]
Yes, it would be nice to have that option. The country names could for example be included when requesting the metadata, as is the case in the Stata command.

To do that, however, and given how the API works, I would need to completely rewrite the command to use the JSON API (which the Stata command uses) rather than the CSV API (which the R command uses). I do intend to do this at some point, not just because of this but also because the CSV API was always a kind of hack and the JSON API works better. But it will take some time, and I can't give any precise timeline at this point.

In the meantime, our country codes mostly follow the ISO 3166-1 alpha-2 standard, so the [countrycode](https://cran.r-project.org/web/packages/countrycode/index.html) package should work quite well. For the rest, here is the complete list of codes in the database: [country-codes.xlsx](https://github.com/WIDworld/wid-r-tool/files/4776661/country-codes.xlsx).

**Comment by thomasblanchet** [comment]
I've updated the package as I've explained, so that now when you request metadata it provides the full names of country/regions. Also, the documentation now redirects to https://wid.world/codes-dictionary/, a new, more complete and more up-to-date description of the database structure.
